public class Car {
	//class body
	
    //create a method, and write all the code inside method (for now)
    //public -> access modifier
    //void   -> return type (what are we returning from this method). Void means NOTHING.
    //switchOn -> method name (no spaces allowed, no -, camelCase)
    public void switchOn(){
        //method body
        system.debug('switching on the car now...');
    }
}

//no code outside of the class