// Calculator c = new Calculator();
// integer sum1 = c.add(12, 25);
// system.debug('sum1 is ' + sum1);

// integer sum2 = c.add(10,15,25);
// system.debug('sum2: ' + sum2);

// integer sum3 = c.add(sum1, sum2);
// system.debug('sum3: ' + sum3);

// string sum4 = c.add('hello', 'hello');
// system.debug('sum4 => ' + sum4);

// decimal sum5 = c.add(5.5,1.5);
// system.debug('sum5 => ' + sum5);

CalculatorProgram cp = new CalculatorProgram();
cp.run();